### ISSUE TITLE
Openhab Thing query

### ISSUE THREAD

**Issue by clinophobic** [lillaeriika/NSPanel#1]
Thanks for this amazing project.

Would you have a copy of your thing and item setup in Openhab to allow for 2 way communication between the panel and Openhab.

**Comment by cablesandcoffee** [comment]
Hi! So glad that it's of some use for you! I just uploaded a folder with four files with the yaml code for my mqtt things in Openhab.
This github is a bit messy right now. I will try to clean things up soon. I've re-written alot of the esphome code and also updated the tft-file.
